### ISSUE TITLE
Problem with "before" / "after" options

### ISSUE THREAD

**Issue by xVinniVx** [stefangabos/Zebra_Mptt#11] opened 2020-02-12 06:16 UTC
There is an issue with **MOVE** function.

I have a very simple category list - no children, just something like this:

[1] TV
[2] Apple
[3] Samsung
[4] Sony
[5] LG
[6] Huawei

When I'm trying to do:  **move(5,3, 'before')** or **move(5,2, 'after)** I receive error:
```
**Warning**:  array_keys() expects parameter 1 to be array, boolean given in **zebra_mptt/zebra_mptt.php** on line **1095**
**Warning**:  array_search() expects parameter 2 to be array, null given in **zebra_mptt/zebra_mptt.php** on line **1096**
```

I'm using PHP 7.2.

When I do simple **move(6,3)** without **_before / after_** - everything is fine. Only **_before / after_** commands are making this warning, and the script doesn't work properly.

Is Zebra_Mptt still maintained?

**Comment by stefangabos** [comment] 2020-02-12 08:04
I am unable to reproduce this. 
Here's my code
```php

// add main category
$tv = $mptt->add(0, 'Tv');

// add subcategories
$apple = $mptt->add($tv, 'Apple');
$samsung = $mptt->add($tv, 'Samsung');
$sony = $mptt->add($tv, 'Sony');
$lg = $mptt->add($tv, 'LG');
$huawei = $mptt->add($tv, 'Huawei');

// move item
$mptt->move($lg, $samsung, 'before');
```

**Comment by xVinniVx** [comment] 2020-02-12 08:15
Try this then:
Database:
```
CREATE TABLE `kategorie-test` (
  `id` int(11) NOT NULL,
  `name` varchar(255) CHARACTER SET latin2 NOT NULL,
  `lft` int(11) NOT NULL DEFAULT '0',
  `rgt` int(11) NOT NULL DEFAULT '0',
  `parent` int(11) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
```

```
INSERT INTO `kategorie-test` (`id`, `name`, `lft`, `rgt`, `parent`) VALUES
(1, 'Akcesoria samochodowe', 3, 4, 0),
(2, 'Części i akcesoria motocyklowe', 15, 16, 0),
(3, 'Części samochodowe', 7, 8, 0),
(4, 'Narzędzia i sprzęt warsztatowy', 13, 14, 0),
(5, 'Opony i felgi', 11, 12, 0),
(6, 'test', 5, 6, 0),
(7, 'Zawsze sięgaj gwiazd', 1, 2, 0),
(8, 'asdasdfgasgasdg', 9, 10, 0);
```

Then create php file and do only:

```
$mptt = new Zebra_Mptt($mysqli, 'kategorie-test', 'id', 'name');
$mptt->move(4, 8, 'before');  <--- ERROR
```
but other move methods, like:
`$mptt->move(4, 0, 6);  <--- works great`


I receive the same warning as in 1st post. I don't know where is the problem.

**Comment by stefangabos** [comment] 2020-02-12 08:38
Ok, i am able to reproduce the issue with this data and I am looking into it now

**Comment by xVinniVx** [comment] 2020-02-12 08:45
Ok. The issue is not there if you are changing position / order within subcategories. But if you have only main categories - there is this error.

**Comment by stefangabos** [comment] 2020-02-12 09:04
Should be fixed now. Please download again and let me know if it works

**Comment by xVinniVx** [comment] 2020-02-12 09:30
Yes, it's working now but there must be something wrong with the order.
Sometimes - from time to time - when I'm moving node - for example:
**$mptt->move(6, 2, 'after');**
the result is that Node 6 is **AFTER node 3**. Then I repeat the script and the node then is after Node 2.  Very strange behaviour. 

Now i did: $mptt->move(6, 4, 'after'); and it went after 7 (the order was: 2,4,7,1...)

Could you look at this?

**Comment by stefangabos** [comment] 2020-02-12 09:59
I always get the correct results

```php
mysqli_query($connection, 'TRUNCATE TABLE mptt');
mysqli_query($connection, "
    INSERT INTO `mptt` (`id`, `title`, `lft`, `rgt`, `parent`) VALUES
    (1, 'Akcesoria samochodowe', 3, 4, 0),
    (2, 'Części i akcesoria motocyklowe', 15, 16, 0),
    (3, 'Części samochodowe', 7, 8, 0),
    (4, 'Narzędzia i sprzęt warsztatowy', 13, 14, 0),
    (5, 'Opony i felgi', 11, 12, 0),
    (6, 'test', 5, 6, 0),
    (7, 'Zawsze sięgaj gwiazd', 1, 2, 0),
    (8, 'asdasdfgasgasdg', 9, 10, 0);
");

$mptt->move(6, 2, 'after');

// data in the database as a multidimensional array
print_r('<p>The entire tree');
print_r('<pre>');
print_r($mptt->get_tree());
print_r('</pre>');
```

**Comment by xVinniVx** [comment] 2020-02-12 10:08
Ok, with this database do:
$mptt->move(7, 5, 'after');

Is everything ok? 
happened for me. You can reproduce this error.
I inserted this:
```
  INSERT INTO `mptt` (`id`, `title`, `lft`, `rgt`, `parent`) VALUES
    (1, 'Akcesoria samochodowe', 3, 4, 0),
    (2, 'Części i akcesoria motocyklowe', 15, 16, 0),
    (3, 'Części samochodowe', 7, 8, 0),
    (4, 'Narzędzia i sprzęt warsztatowy', 13, 14, 0),
    (5, 'Opony i felgi', 11, 12, 0),
    (6, 'test', 5, 6, 0),
    (7, 'Zawsze sięgaj gwiazd', 1, 2, 0),
    (8, 'asdasdfgasgasdg', 9, 10, 0);
```
into the database, and did:
```
$mptt = new Zebra_Mptt($mysqli, 'mptt', 'id', 'title');
$mptt->move(7, 5, 'after');
```

Node 7 is now after node 4. Why?

**Comment by stefangabos** [comment] 2020-02-12 10:14
ok, i see. working on it

**Comment by stefangabos** [comment] 2020-02-12 10:24
please check again now

**Comment by xVinniVx** [comment] 2020-02-12 10:41
Everything seems ok now - but please, leave issue open till tomorrow. I will do better tests after the dinner.

Great work. I love this script.

**Comment by stefangabos** [comment] 2020-02-12 10:45
ok. please star the project if you like it. thank you!

**Comment by xVinniVx** [comment] 2020-02-13 21:24
All is OK now - I didn't find any bug regarding changing order / branches.

**Comment by stefangabos** [comment] 2020-02-13 21:25
ok, thanks!

**Closed by stefangabos** 2020-02-13 21:25 UTC
